// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCujLy2lPNaWXnSujufVen3croBIdA4zs',
    appId: '1:964833230402:web:d7663809041191bc9a77db',
    messagingSenderId: '964833230402',
    projectId: 'fpush-31789',
    authDomain: 'fpush-31789.firebaseapp.com',
    storageBucket: 'fpush-31789.firebasestorage.app',
    measurementId: 'G-NLFSR58728',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKm-8sftyZDG4500f42gtIIDK1_WBpFm4',
    appId: '1:964833230402:android:45b206fdfda794129a77db',
    messagingSenderId: '964833230402',
    projectId: 'fpush-31789',
    storageBucket: 'fpush-31789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6sWPeOD14g2QsBV2_jMAzLmOB5bselMQ',
    appId: '1:964833230402:ios:183604b3787c2b419a77db',
    messagingSenderId: '964833230402',
    projectId: 'fpush-31789',
    storageBucket: 'fpush-31789.firebasestorage.app',
    iosBundleId: 'com.example.fPush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6sWPeOD14g2QsBV2_jMAzLmOB5bselMQ',
    appId: '1:964833230402:ios:183604b3787c2b419a77db',
    messagingSenderId: '964833230402',
    projectId: 'fpush-31789',
    storageBucket: 'fpush-31789.firebasestorage.app',
    iosBundleId: 'com.example.fPush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCujLy2lPNaWXnSujufVen3croBIdA4zs',
    appId: '1:964833230402:web:6c5c4f3572f108129a77db',
    messagingSenderId: '964833230402',
    projectId: 'fpush-31789',
    authDomain: 'fpush-31789.firebaseapp.com',
    storageBucket: 'fpush-31789.firebasestorage.app',
    measurementId: 'G-J8FGJVKJS4',
  );
}
